AWSTemplateFormatVersion: "2010-09-09"
Description: Builder Session - EKS Product Association
Parameters:
  PortfolioStackName:
    Type: String
    Default: sc-portfolio
    Description: Enter the Service Catalog Portfolio stack name
  EKSStackName:
    Type: String
    Default: sc-simple-eks
    Description: Enter the EKS cluster service catalog stack name
Resources:
################## PRODUCT ASSOCIATIONS #################
  EKSAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties: 
      PortfolioId:
        Fn::ImportValue:
          !Sub "${PortfolioStackName}-PortfolioId"
      ProductId: 
        Fn::ImportValue:
          !Sub "${EKSStackName}-ProductPA"

################## LAUNCH ROLE CONSTRAINT #################
  SCEKSLaunchRoleConst:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      Description: Service Catalog uses this role to launch the product
      PortfolioId: 
        Fn::ImportValue:
          !Sub "${PortfolioStackName}-PortfolioId"
      ProductId:
        Fn::ImportValue:
          !Sub "${EKSStackName}-ProductPA"
      RoleArn: 
        Fn::ImportValue:
          !Sub "${PortfolioStackName}-LaunchRole"
    DependsOn:
      - EKSAssociation